/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * Regenerate with: pnpm run generate-schema
 */

export interface paths {}
export interface webhooks {}
export interface components {
  schemas: {};
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
